### ISSUE TITLE
IndexError: index 8 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by soumitra9** [svpino/tf_object_detection_cm#3]
Hi, I am getting the following error. Need help.

Traceback (most recent call last):
  File "confusion_matrix.py", line 134, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "confusion_matrix.py", line 129, in main
    confusion_matrix = process_detections(FLAGS.detections_record, categories)
  File "confusion_matrix.py", line 90, in process_detections
    confusion_matrix[groundtruth_classes[i] - 1][confusion_matrix.shape[1] - 1] += 1
IndexError: index 8 is out of bounds for axis 0 with size 3

**Comment by svpino** [comment]
It seems to be a problem with the classes you have specified. Make sure the ground truth classes are all represented properly.

**Comment by wbowditch** [comment]
I'm getting a similar error, I'll debug to make sure the matches dimensions make sense:

```
$ python confusion_matrix.py --detections_record=detections.record --label_map=label_map.pbtxt 
Traceback (most recent call last):
  File "confusion_matrix.py", line 133, in <module>
    tf.app.run(main)
  File "/Users/williamhackathon/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "confusion_matrix.py", line 128, in main
    confusion_matrix = process_detections(FLAGS.detections_record, categories)
  File "confusion_matrix.py", line 87, in process_detections
    confusion_matrix[groundtruth_classes[i] - 1][detection_classes[int(matches[matches[:,0] == i, 1][0])] - 1] += 1 
IndexError: index 6 is out of bounds for axis 0 with size 3
```

**Comment by wbowditch** [comment]
Found the issue, max_num_classes is hardcoded to 2 on line 129:
`    categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=2, use_display_name=True)
`

**Comment by svpino** [comment]
Good catch. I fixed it already.

**Comment by mohammadakz** [comment]
Hi I am running the code on a cluster, I checked the comments but I still have this problem:


Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1

WARNING:tensorflow:From ./Confusion.py:36: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
Traceback (most recent call last):
  File "./Confusion.py", line 133, in <module>
    tf.app.run(main)
  File "/scratch/moakbarz/models/research/object_detection/tensorflowm/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./Confusion.py", line 128, in main
    confusion_matrix = process_detections(FLAGS.detections_record, categories)
  File "./Confusion.py", line 87, in process_detections
    confusion_matrix[groundtruth_classes[i] - 1][detection_classes[int(matches[matches[:,0] == i, 1][0])] - 1] += 1 
IndexError: index 5 is out of bounds for axis 0 with size 5
